version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
      - image: nats:2.1.0-scratch
    working_directory: ~/repo
    environment:
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout
      - run: sudo apt-get update && sudo apt-get -y install autoconf automake libtool curl make g++ unzip
      - run: curl -L https://github.com/protocolbuffers/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip -o protoc.zip
      - run: unzip protoc.zip && sudo cp ./bin/protoc /usr/bin/protoc
      - run: ./mvnw clean verify sonar:sonar -Dsonar.projectKey=jibitters_java-notifier -Dsonar.organization=jibitters -Dsonar.host.url=https://sonarcloud.io -B
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud
